import React from 'react';
import { Link } from 'react-router-dom';
import { ArrowRight, CheckCircle2, BarChart3, Users, Clock } from 'lucide-react';
import Navbar from '../components/Navbar';
import heroIll from '../assets/hero2.svg';

export default function Home() {
  return (
    <div className="min-h-screen bg-slate-50 font-sans text-slate-900">
      <Navbar />

      {/* HERO SECTION */}
      <div className="bg-white">
        <div className="max-w-7xl mx-auto px-4 py-20 sm:px-6 lg:px-8 grid md:grid-cols-2 gap-12 items-center">
          <div className="space-y-6">
            <h1 className="text-4xl md:text-5xl font-extrabold tracking-tight leading-tight text-slate-900">Unified Grievance Redressal Portal</h1>
            <p className="text-lg text-slate-600 max-w-xl leading-relaxed">A government-grade citizen grievance platform — submit complaints via text, images or voice, track progress, and view official responses transparently.</p>
            <div className="flex flex-wrap gap-4 pt-4">
              <Link to="/citizen" className="bg-orange-600 hover:bg-orange-700 text-white px-6 py-3 rounded-md font-semibold shadow-md flex items-center gap-2">Lodge Complaint <ArrowRight size={18} /></Link>
              <Link to="/contact" className="bg-white border border-slate-200 px-6 py-3 rounded-md font-semibold text-slate-800">Contact Helpdesk</Link>
            </div>
            <div className="mt-6 text-sm text-slate-500"><strong>Note:</strong> This portal is maintained by the municipal administration. All complaints are tracked with unique IDs and SLAs.</div>
          </div>
          <div className="flex items-center justify-center">
            <div className="w-full max-w-lg shadow rounded-2xl overflow-hidden border border-slate-100">
              <img src={heroIll} alt="hero professional" className="w-full h-64 object-cover" />
            </div>
          </div>
        </div>
      </div>

      {/* STATS STRIP */}
      <div className="bg-white border-b border-slate-200">
        <div className="max-w-7xl mx-auto px-4 py-8 grid grid-cols-2 md:grid-cols-4 gap-8">
           {[
             { label: "Total Grievances", val: "1.2M+", icon: BarChart3 },
             { label: "Resolved Cases", val: "98%", icon: CheckCircle2, color: "text-green-600" },
             { label: "Avg Response Time", val: "4 Hrs", icon: Clock },
             { label: "Active Officers", val: "15k+", icon: Users },
           ].map((stat, idx) => (
             <div key={idx} className="flex items-center gap-4">
                <div className={`p-3 rounded-lg bg-slate-50 ${stat.color || 'text-slate-600'}`}>
                  <stat.icon size={24} />
                </div>
                <div>
                  <div className="text-2xl font-bold text-slate-900">{stat.val}</div>
                  <div className="text-xs font-bold text-slate-500 uppercase">{stat.label}</div>
                </div>
             </div>
           ))}
        </div>
      </div>

      {/* FEATURES SECTION */}
      <div className="py-20 bg-slate-50">
        <div className="max-w-7xl mx-auto px-4">
          <div className="text-center mb-16">
            <h2 className="text-3xl font-bold text-slate-900">Why choose CivicConnect?</h2>
            <p className="text-slate-500 mt-2">Next-generation governance powered by Agentic AI</p>
          </div>
          
          <div className="grid md:grid-cols-3 gap-8">
            {/* Card 1 */}
            <div className="bg-white p-8 rounded-2xl shadow-sm border border-slate-200 hover:shadow-xl transition-shadow">
              <div className="w-12 h-12 bg-blue-100 rounded-lg flex items-center justify-center text-blue-600 mb-6">
                <Users size={24} />
              </div>
              <h3 className="text-xl font-bold text-slate-800 mb-3">AI-Powered Sorting</h3>
              <p className="text-slate-600 leading-relaxed">
                Our Triage Agent automatically categorizes complaints and assigns severity scores, ensuring critical issues get handled first.
              </p>
            </div>
            
            {/* Card 2 */}
            <div className="bg-white p-8 rounded-2xl shadow-sm border border-slate-200 hover:shadow-xl transition-shadow">
              <div className="w-12 h-12 bg-orange-100 rounded-lg flex items-center justify-center text-orange-600 mb-6">
                <Clock size={24} />
              </div>
              <h3 className="text-xl font-bold text-slate-800 mb-3">Instant Drafting</h3>
              <p className="text-slate-600 leading-relaxed">
                Officers receive pre-drafted legal notices generated by AI, reducing paperwork time by 90% and speeding up resolutions.
              </p>
            </div>

            {/* Card 3 */}
            <div className="bg-white p-8 rounded-2xl shadow-sm border border-slate-200 hover:shadow-xl transition-shadow">
              <div className="w-12 h-12 bg-green-100 rounded-lg flex items-center justify-center text-green-600 mb-6">
                <CheckCircle2 size={24} />
              </div>
              <h3 className="text-xl font-bold text-slate-800 mb-3">Visual Verification</h3>
              <p className="text-slate-600 leading-relaxed">
                Computer Vision compares "Before" and "After" photos to prevent fake closures and ensure 100% accountability.
              </p>
            </div>
          </div>
        </div>
      </div>

      {/* ROLE CARDS - align with Excalidraw roles */}
      <div className="py-12 bg-white">
        <div className="max-w-7xl mx-auto px-4">
          <h3 className="text-center text-2xl font-bold mb-8">Choose your access</h3>
          <div className="grid md:grid-cols-3 gap-6">
            <div className="p-6 rounded-2xl border border-slate-100 shadow-sm text-center">
              <div className="w-16 h-16 rounded-full bg-blue-50 mx-auto flex items-center justify-center text-blue-600 font-bold mb-4">C</div>
              <h4 className="font-bold">Citizen</h4>
              <p className="text-sm text-slate-500 mt-2">Login, lodge complaints via voice/photo, track status, provide feedback.</p>
              <Link to="/citizen" className="inline-block mt-4 text-sm font-semibold text-orange-600">Open Portal →</Link>
            </div>

            <div className="p-6 rounded-2xl border border-slate-100 shadow-sm text-center">
              <div className="w-16 h-16 rounded-full bg-green-50 mx-auto flex items-center justify-center text-green-600 font-bold mb-4">O</div>
              <h4 className="font-bold">Officer</h4>
              <p className="text-sm text-slate-500 mt-2">Assigned cases, AI drafting, upload evidence, close with photos.</p>
              <Link to="/officer" className="inline-block mt-4 text-sm font-semibold text-orange-600">Officer Login →</Link>
            </div>

            <div className="p-6 rounded-2xl border border-slate-100 shadow-sm text-center">
              <div className="w-16 h-16 rounded-full bg-orange-50 mx-auto flex items-center justify-center text-orange-600 font-bold mb-4">A</div>
              <h4 className="font-bold">Admin</h4>
              <p className="text-sm text-slate-500 mt-2">Manage departments, employees, escalation rules and feedback.</p>
              <Link to="/admin" className="inline-block mt-4 text-sm font-semibold text-orange-600">Admin Console →</Link>
            </div>
          </div>
        </div>
      </div>

      {/* FOOTER */}
      <footer className="bg-slate-900 text-slate-400 py-12 border-t border-slate-800">
        <div className="max-w-7xl mx-auto px-4 grid md:grid-cols-4 gap-8 text-sm">
          <div>
            <h4 className="text-white font-bold mb-4">CivicConnect</h4>
            <p>Empowering citizens through transparent and efficient governance technology.</p>
          </div>
          <div>
            <h4 className="text-white font-bold mb-4">Quick Links</h4>
            <ul className="space-y-2">
              <li><a href="#" className="hover:text-white">Home</a></li>
              <li><a href="#" className="hover:text-white">Lodge Grievance</a></li>
              <li><a href="#" className="hover:text-white">Track Status</a></li>
            </ul>
          </div>
          <div>
            <h4 className="text-white font-bold mb-4">Legal</h4>
            <ul className="space-y-2">
              <li><a href="#" className="hover:text-white">Privacy Policy</a></li>
              <li><a href="#" className="hover:text-white">Terms of Service</a></li>
            </ul>
          </div>
          <div>
            <h4 className="text-white font-bold mb-4">Contact</h4>
            <p>Helpline: 1800-11-2233</p>
            <p>Email: support@civicconnect.gov.in</p>
          </div>
        </div>
      </footer>
    </div>
  );
}